name: Secure Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
    steps:
      - uses: actions/checkout@v4  
      - name: Scan dependencies
        uses: snyk/actions/node@master
        with:
          args: --severity-threshold=high