name: Code Quality - Super Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run GitHub Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
          VALIDATE_PYTHON: true
          VALIDATE_BASH: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MARKDOWN: true
